dist: trusty
language: php
php:
- 7.2
- 7.3
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
  - "$HOME/.composer/cache"
install:
- nvm install 12
- npm install
- composer install
script:
- composer test
before_deploy:
- npm run zip
- ls -la my-snow-monkey.zip
- export RELEASE_FILE=$(ls my-snow-monkey.zip)
deploy:
  provider: releases
  api_key:
    secure: d898VhJi+9vWKLaRrTzkDkt6ycDbLv2AQ8V68PPtKBbHbqdiv6rOfNN/nD55wbmiXvI20O6xoz0eUl1+33qcnDC8N1q4YhqqcR1g85qlM6kPmTFfDyt61OJd4e7DUVEN6f0I8/JJM3rPWSXhWNKruIXUGDkZBKbLOKUaXWoJyA1/I8gV1K9avd4c6VQccG7blzbQFhtgK5AcbjNk46U3uXVozPtRjwMfpzAtcQE/RmNbMISjp7YchBnEk+SdhHgX/MWL5fDnAO8TAylmh4D+j/KGRcBzdHEuInJvy+xfwTS5nvxx2Y9R3plYqM/0PvGB6iSjRdfc9/OZsWgEOuKsvSA9bKoU0K111ybYeBqa8Z35UvBD0qV+zNlEE0CdHBOTNiX/XjC3S3W6fj5byejoe1wx4eWK4eguGO0Vxo7657KRVlmctWAGg7i+5kRNsNnaQIjB8D65WeWAiDi0PE0uNZQ+V2Y98VDCYDnE6g0BM3njmD1XoQRQ1E2AzQXoOOK58eXiW0koRwMGVxObX1KAxrMUo24UgCQuAR3WQ0/wkhrmvQswsFKkrFtpEp7FBtz8u/H4XhJBo+lomnfCO0Z1LLxxzIlBE0wRRSChEcLer67vvub+Kcl5RVTQ+PA9pxRO88TLsWo4B0nSvBzKQng27uZk8icHpXDQ2u5DNIkMiZ0=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: inc2734/my-snow-monkey
    php: 7.2
